buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.3"
    }
}
plugins {
    id 'java'
    id 'application'
}

apply plugin: 'com.github.johnrengelman.shadow'

mainClassName = 'gadgetinspector.GadgetInspector'

repositories {
    mavenCentral()
}

dependencies {
    compile "org.ow2.asm:asm:9.2"
    compile "org.ow2.asm:asm-commons:9.2"
    compile "com.google.guava:guava:26.0-jre"
    compile 'org.slf4j:slf4j-api:1.7.25'
    compile 'org.slf4j:slf4j-log4j12:1.7.25'
    compile 'org.apache.httpcomponents:httpclient:4.5.3'
    compile 'org.apache.httpcomponents:httpmime:4.5.3'
    compile 'org.apache.httpcomponents:httpasyncclient:4.1.4'
    compile 'org.jsoup:jsoup:1.10.3'

    if (project.hasProperty("inspectGroup")) {
        compile "${project.inspectGroup}:${project.inspectName}:${project.inspectVersion}"
    }
}

if (project.hasProperty("inspectConfig")) {
    task runInspect(type: JavaExec) {
        classpath = sourceSets.main.runtimeClasspath
        main = "gadgetinspector.GadgetInspector"
        args = ["--config", project.inspectConfig]
    }
}